"""initial schema

Revision ID: 1338bc6e7896
Revises: 
Create Date: 2026-05-25 22:33:01.794866
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1338bc6e7896'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vat', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('manufacturer_name', sa.String(length=512), nullable=True),
    sa.Column('family_code', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('passport', sa.JSON(), nullable=False),
    sa.Column('source_documents', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_family_code'), ['family_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_status'), ['status'], unique=False)

    op.create_table('batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('lot', sa.String(length=255), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('production_date', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_product_id'), ['product_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=True),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_product_id'), ['product_id'], unique=False)

    op.create_table('extraction_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_jobs_product_id'), ['product_id'], unique=False)

    op.create_table('versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('passport_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_versions_product_id'), ['product_id'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('dimensions', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.String(length=64), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('production_date', sa.String(length=64), nullable=True),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_batch_id'))

    op.drop_table('items')
    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_versions_product_id'))

    op.drop_table('versions')
    with op.batch_alter_table('extraction_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_jobs_product_id'))

    op.drop_table('extraction_jobs')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_product_id'))

    op.drop_table('documents')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_product_id'))

    op.drop_table('batches')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_status'))
        batch_op.drop_index(batch_op.f('ix_products_family_code'))
        batch_op.drop_index(batch_op.f('ix_products_company_id'))

    op.drop_table('products')
    op.drop_table('companies')
    # ### end Alembic commands ###
