#!/bin/bash
# EC2 user-data: runs once on first boot of the DeePPy prod instance.
#
# Assumes:
#   • Amazon Linux 2023 AMI
#   • IAM instance profile "deeppy-prod-ec2" attached (SSM read access)
#   • A second EBS volume attached as /dev/sdb (aka /dev/nvme1n1) for /opt/deeppy
#
# Fill in REPO_URL below before launching, or bake it into a launch template.
#
# Progress log at:  /var/log/deeppy-bootstrap.log

set -euo pipefail
exec > >(tee -a /var/log/deeppy-bootstrap.log) 2>&1
echo "===== DeePPy bootstrap starting at $(date -Iseconds) ====="

# ── 1. Config ─────────────────────────────────────────────────────────────
REGION="eu-central-1"
REPO_URL="https://github.com/Mousa-Becquerel/deeppy.git"
APP_DIR="/opt/deeppy/app"
DATA_ROOT="/opt/deeppy"
DATA_DEVICE="/dev/nvme1n1"                    # EBS volume device — verify with `lsblk` after launch

# ── 2. System packages: Docker + compose + git + awscli ───────────────────
dnf update -y
dnf install -y docker git

# Docker Compose v2 as a plugin (the `docker compose` command).
mkdir -p /usr/local/lib/docker/cli-plugins
curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

systemctl enable --now docker
usermod -aG docker ec2-user

# AWS CLI v2 (Amazon Linux 2023 doesn't ship it by default).
if ! command -v aws >/dev/null; then
  curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
  unzip -q /tmp/awscliv2.zip -d /tmp
  /tmp/aws/install
fi

# ── 3. Mount the data EBS volume at /opt/deeppy ───────────────────────────
mkdir -p "${DATA_ROOT}"
if [ -b "${DATA_DEVICE}" ]; then
  if ! blkid "${DATA_DEVICE}" >/dev/null 2>&1; then
    echo "Formatting ${DATA_DEVICE} as ext4 (first boot)"
    mkfs.ext4 "${DATA_DEVICE}"
  fi
  # fstab entry so it comes back on reboot.
  UUID=$(blkid -s UUID -o value "${DATA_DEVICE}")
  if ! grep -q "${UUID}" /etc/fstab; then
    echo "UUID=${UUID}  ${DATA_ROOT}  ext4  defaults,nofail  0  2" >> /etc/fstab
  fi
  mount -a
else
  echo "WARNING: ${DATA_DEVICE} not present. Falling back to the root volume for /opt/deeppy — resize the root EBS if you go to production."
fi

# App-owned subdirs. api container writes as UID 0 today; tighten later.
mkdir -p "${DATA_ROOT}"/{data,uploads,caddy-data,caddy-config,app}
chown -R ec2-user:ec2-user "${DATA_ROOT}"

# ── 4. Clone the app repo ─────────────────────────────────────────────────
if [ "${REPO_URL}" = "__FILL_ME_IN__" ]; then
  echo "ERROR: REPO_URL not set in user-data. Aborting before secrets fetch."
  exit 1
fi
if [ ! -d "${APP_DIR}/.git" ]; then
  git clone "${REPO_URL}" "${APP_DIR}"
fi
chown -R ec2-user:ec2-user "${APP_DIR}"

# ── 5. Pull secrets from SSM → write .env ────────────────────────────────-
# Uses the instance's IAM role — no keys on disk.
fetch() {
  aws ssm get-parameter --with-decryption --region "${REGION}" \
    --name "$1" --query Parameter.Value --output text
}
JWT_SECRET=$(fetch deeppy_prod_JWT_SECRET)
GOOGLE_API_KEY=$(fetch deeppy_prod_GOOGLE_API_KEY)
OPENAI_API_KEY=$(fetch deeppy_prod_OPENAI_API_KEY)

ENV_FILE="${APP_DIR}/deploy/.env"
cat > "${ENV_FILE}" <<EOF
# Generated by user-data at $(date -Iseconds). DO NOT COMMIT.
JWT_SECRET=${JWT_SECRET}
GOOGLE_API_KEY=${GOOGLE_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}
# Empty DEPLOY_DOMAIN = HTTP-only smoke-test mode. Set to your FQDN then
# restart the web service to switch to auto-TLS.
DEPLOY_DOMAIN=
LETSENCRYPT_EMAIL=m.sondoqah@becquerelinstitute.eu
# Cookies stay non-Secure until we have HTTPS. Flip to true after adding the domain.
COOKIE_SECURE=false
EOF
chmod 600 "${ENV_FILE}"
chown ec2-user:ec2-user "${ENV_FILE}"

# ── 6. Boot the stack ─────────────────────────────────────────────────────
cd "${APP_DIR}/deploy"
docker compose -f docker-compose.prod.yml --env-file .env up -d --build

echo "===== DeePPy bootstrap DONE at $(date -Iseconds) ====="
echo "Check: curl http://localhost/api/health"
